---
name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  ci:
    uses: robotpy/build-actions/.github/workflows/package-ci.yml@v2025
    with:
      artifactory_repo_type: vendor
      enable_raspbian: false
    secrets:
      META_REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
      RTD_WEBHOOK: ${{ secrets.RTD_WEBHOOK }}
      WPI_ARTIFACTORY_USERNAME: ${{ secrets.WPI_ARTIFACTORY_USERNAME }}
      WPI_ARTIFACTORY_TOKEN: ${{ secrets.WPI_ARTIFACTORY_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_PASSWORD }}

  test:
    runs-on: ${{ matrix.os }}
    needs: ci
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-13", "windows-2022"]
        python_version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - uses: actions/download-artifact@v4
      with:
        pattern: pypi-${{ runner.os }}-${{ matrix.python_version }}
        path: dist/
    - name: Install deps
      run: |
        pip install 'robotpy[commands2]<2026.0.0,>=2025.0.0b3' numpy pytest
        pip install dist/*
    - name: Run tests
      run: bash examples/run_tests.sh
      shell: bash
